### ISSUE TITLE
Section data tied to step number

### ISSUE THREAD

**Issue by mixcas** [interglobalvision/applaya#21]
Just realized our data is tied to the step number, which could cause potential issues. This an example of a section data.

```
{
  "_id": "Lah9PjaN72dRBXhXo",
  "step": 2,
  "userId": "hPLPxWKuRnZvb8E9p",
  "applicationId": "ETs6ucCucWAjeavXZ",
  "data": {
    "accept": true
  },
  "validated": true
}
```

What if steps are added or removed, then the step number won't match.

It smells bad like that. I'd like to see the chance of changing `step` for `name` instead as our reference for section data. `name` is defined in the `steps.js`.

**Comment by varffs** [comment]
Hmm not sure how much of an issue this really is tho, to be adding or removing steps after launch would be a bad thing to do anyhow. It could only be an indication of a premature launch which would be outside of the actual scope of this codebase?

But considering we want to save a progress value then perhaps we could add more to this session data allowing us to do a simple check against steps length on login or something?
